name: "Get GitHub App Token PowerShell"
description: "GitHub Action for creating a GitHub App installation access token using PowerShell."
author: "Benedict Schmieder"
branding:
  icon: "lock"
  color: "gray-dark"
inputs:
  app-id:
    description: "GitHub App ID"
    required: true 
  private-key:
    description: "GitHub App private key"
    required: true
outputs:
  token:
    description: "GitHub installation access token"
    value: ${{ steps.get-token.outputs.token }}
runs:
  using: "composite"
  steps:
    - name: Get-AppToken
      id: get-token
      shell: pwsh
      run: |
        Import-Module $env:GITHUB_ACTION_PATH/Get-GitHubAppToken
        $accessToken = Get-GitHubAppToken -AppId "${{ inputs.app-id }}" -PrivateKey "${{ inputs.private-key }}"
        Write-Output "token=$($accessToken)" >> "$GITHUB_OUTPUT"
        
