#
# Module manifest for module 'Get-GitHubAppToken'
#
# Generated by: Benedict Schmieder
#
# Generated on: 21.02.2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Get-GitHubAppToken.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '5a62a5d4-c3bb-4522-8e4f-525d27bbd1b4'

# Author of this module
Author = 'Benedict Schmieder'

# Copyright statement for this module
Copyright = '(c) Benedict Schmieder. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Generates an access token for a specific GitHub app specified by App ID using a private key as authentication and then outputs it as a string.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '6.0.0'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('jwtPS')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Get-GithubAppToken')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('GitHub', 'CI/CD', 'Runner', 'GitHub App', 'Token', 'Secret', 'Authentication', 'Actions', 'GitHub Actions')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/benedictschmieder/get-github-app-token-ps/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/benedictschmieder/get-github-app-token-ps'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @('jwtPS')

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/benedictschmieder/get-github-app-token-ps/blob/main/README.md'

}

