name: Build and Publish Module

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update PowerShellGet
        shell: pwsh
        run: Install-Module PowerShellGet -Force

      - name: Build and Publish Module
        shell: pwsh
        run: |
          $modulePath = "./Get-GitHubAppToken"
          $repository = "PSGallery"

          #Installing required modules in order for Test-ModuleManifest to complete
          $requiredModules = (Import-PowerShellDataFile "$modulepath/Get-GitHubAppToken.psd1").RequiredModules
          foreach ($module in $requiredModules) {
            Write-Host "Installing $module"
            Install-Module $module -AllowClobber -Force -ErrorAction Stop
            Import-Module $module
          }
          
          $publishParams = @{
            Path        = $modulePath
            NuGetApiKey = $env:apiKey
            Verbose     = $true
            Force       = $true
            Repository  = $repository
            ErrorAction = 'Stop'
          }

          Write-Host "Files in module output:"
          Get-ChildItem $modulePath -Recurse -File | Select-Object -Expand FullName
          Write-Host "Publishing to $repository"

          Publish-Module @publishParams
        env:
          apiKey: ${{ secrets.PSGALLERY_API_KEY }}
