name: Build and Publish Module

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      modulePath: "${{ github.workspace }}/Get-GitHubAppToken"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and Update necessary modules
        shell: pwsh
        run: |
          echo "$env:modulePath"
          $requiredModules = (Import-PowerShellDataFile "$env:modulepath/Get-GitHubAppToken.psd1").RequiredModules + "PowerShellGet"
          foreach ($module in $requiredModules) {
            Write-Host "Installing module $module"
            Install-Module $module -AllowClobber -Force -ErrorAction Stop
          }

      - name: Build and Publish Module
        shell: pwsh
        run: |
          $repository = "PSGallery"
          $publishParams = @{
            Path        = $modulePath
            NuGetApiKey = $env:apiKey
            Verbose     = $true
            Force       = $true
            Repository  = $repository
            ErrorAction = 'Stop'
          }
          Write-Host "Files in module output:"
          Get-ChildItem $modulePath -Recurse -File | Select-Object -Expand FullName
          Write-Host "`nPublishing to repository $repository"
          Publish-Module @publishParams
        env:
          apiKey: ${{ secrets.PSGALLERY_API_KEY }}
